/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSetupDialog: typeof import('./src/components/p0/AccountSetupDialog.vue')['default']
    AddMomentForm: typeof import('./src/components/AddMomentForm.vue')['default']
    BackupSnapshotTable: typeof import('./src/components/p0/BackupSnapshotTable.vue')['default']
    BGMPlayer: typeof import('./src/components/BGMPlayer.vue')['default']
    FallingHearts: typeof import('./src/components/FallingHearts.vue')['default']
    InviteCodeCard: typeof import('./src/components/p0/InviteCodeCard.vue')['default']
    MomentCard: typeof import('./src/components/MomentCard.vue')['default']
    QuestionBankDialog: typeof import('./src/components/QuestionBankDialog.vue')['default']
    ReminderRuleForm: typeof import('./src/components/p0/ReminderRuleForm.vue')['default']
    RequestStatePanel: typeof import('./src/components/p0/RequestStatePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensitiveActionDialog: typeof import('./src/components/p0/SensitiveActionDialog.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    UserProfileDialog: typeof import('./src/components/profile/UserProfileDialog.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
